### ISSUE TITLE
How to decide the value of MFCC_DEC_BITS

### ISSUE THREAD

**Issue by rayeh5** [ARM-software/ML-KWS-for-MCU#106]
Hi,
   Sorry to bother you.
   I am new to the KWS and MFCC.
   Since the definition of MFCC_DEC_BITS value is different between DNN (value 2) and DS_CNN (value 1) model, could someone share how to decide this value?
   Thanks for your time.

ruey-an

**Comment by JeffyCN** [comment]
Check this:
https://github.com/tpeet/ML-KWS-for-MCU/blob/master/helper.py#L298

**Comment by rayeh5** [comment]
Thanks for the information
