### ISSUE TITLE
quant_test with different act_max parameters but produces same content weights.h ?

### ISSUE THREAD

**Issue by jessonwtp** [ARM-software/ML-KWS-for-MCU#122]
Hi All,

When I use quant_test.py to tune act_max parameters (one by one with value 8, 16, 32), I can see the training accuracy, validation accuracy and test accuracy are changing according to different act_max parameters.
But, why I got the same weights.h ? Is it reasonable ?
I can get good accuracy by test.py and label_wav.py.
But when I use this quanted weights file to my embedded device, the test result is great different. 
that's why I think maybe caused by quant function.

It's appreciate if anyone knows the reason and share your experience. 
Thanks.

**Comment by ShintaZachariah** [comment]
Hi All,
what is act_max parameter?

**Comment by jessonwtp** [comment]
Hi Shintzchariah,
act_max is followed by 12 numbers when execute quant_test on ds_cnn model.
If DNN mode, act_max is followed by 5 numbers.
You can refer below linking.
https://github.com/ARM-software/ML-KWS-for-MCU/blob/master/Deployment/Quant_guide.md

**Comment by jessonwtp** [comment]
I'm trying the quant bias shift and out shift which set in the embeded Device side.
