### ISSUE TITLE
Pre-defined Models Quantization

### ISSUE THREAD

**Issue by mehrdadh** [ARM-software/ML-KWS-for-MCU#134]
Are [pre-defined models](https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Pretrained_models) already quantized?
They seem to be in FP32, but what about the parameter values?
I'm mostly interested to know about DS_CNN models.

Thanks

**Comment by saichand07** [comment]
you can visualize model.pb file using netron visualizer, you'll get to know
https://github.com/lutzroeder/netron
