### ISSUE TITLE
Question about the test of trained model

### ISSUE THREAD

**Issue by sailor88128** [ARM-software/ML-KWS-for-MCU#15]
Hi, 
I want to do the F1 and ROC test for the trained model, anyone did this before?

**Comment by NearLinHere** [comment]
I also want to know the answer :D

**Comment by sailor88128** [comment]
Seems tensorflow team provide the tool test_streaming_accuracy , https://www.tensorflow.org/versions/master/tutorials/audio_recognition.

**Comment by NearLinHere** [comment]
@sailor88128 Do you run the tool successfully? I met some problem with it.

**Comment by sailor88128** [comment]
I ran it successfully. It need the new version bazel tool (0.5.4 seems lack of sth, updated it to 0.11.0), and the complete tensorflow folder. @NearLinHere

**Comment by NearLinHere** [comment]
@sailor88128 I see. Thank you.

**Comment by navsuda** [comment]
@sailor88128, You got it.  

Closing the issue.
