### ISSUE TITLE
GCC compilation

### ISSUE THREAD

**Issue by kdpatino** [ARM-software/ML-KWS-for-MCU#18]
Hello,

* Could I compile this project with GCC? 
* Do you have any examples of **CMAKE** or any open source tool?

Thank You in advance!

Kevin Patino

**Comment by navsuda** [comment]
Hi @kdpatino,
- It is possible to compile the project (specific to a particular dev board) using gcc-arm tools. This link has details on how to export an mbed-online project to compile locally using gcc tools: https://os.mbed.com/handbook/Exporting-to-GCC-ARM-Embedded
- Unfortunately, we do not have examples of CMAKE to compile the examples.

**Comment by oneway3124** [comment]
Hi navsuda,

I have one same development as this site referred, but the mbed compile is so complex that I have cost one day for this problem.

david.wang

**Comment by navsuda** [comment]
Added an example to compile without the need for mbed-cli here: [https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Deployment/Examples/simple_test_k64f_gcc](https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Deployment/Examples/simple_test_k64f_gcc). Hope it helps.

**Comment by oneway3124** [comment]
@navsuda 
Your example help me compile successfully.
What's more, I want to know the file folder which you added . Where did they come from ?

**Comment by navsuda** [comment]
Hi @oneway3124,
You can get that by creating a simple hello world project on [mbed online compiler](https://os.mbed.com/compiler/) with the specific board you are targeting and then export with Make-GNU-ARM toolchain as described [here](https://os.mbed.com/handbook/Exporting-to-Make).

**Comment by navsuda** [comment]
Closing the issue, please reopen it if you still face the issue.
