### ISSUE TITLE
Issue running with F411RE

### ISSUE THREAD

**Issue by mridup** [ARM-software/ML-KWS-for-MCU#20]
Hi,
I tried to execute the kws_simple_test example as given in https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Deployment

Board used is NUCLEO_F411RE.
The program crashes in the following line:
KWS kws(audio_buffer,scratch_buffer);
in main.cpp of Examples/simple_test

Did not investigate further but these examples seem tested on Nucleo boards?

regards,
Mridu

**Comment by mridup** [comment]
issue resolved when using global buffers.

**Comment by ccnankai** [comment]
@mridup 
In the quantization process, how to get the value of the quantization ranges -- act_max in quant_test.py .
how to set the specific value of the parameter act_max ( x 0 0 0 0 0 0 0 0 0 0 0 ) ?
