### ISSUE TITLE
there are  one error when I try to deploy on target.

### ISSUE THREAD

**Issue by oneway3124** [ARM-software/ML-KWS-for-MCU#24]
1.Build and run a simple KWS inference
2.mbed new kws_simple_test --mbedlib
3.  ERROR  An error occurred while unpacking library archive ".bld\.rev-5aab5a7997ee.zip" in "c:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment\kws_simple_test\mbed"

**Comment by oneway3124** [comment]
This issue has be fixed. At the same time, when I was compiling the kws_realtime_test，
![qq 20180427150815](https://user-images.githubusercontent.com/3787176/39349269-e3f4374e-4a2c-11e8-81e2-c429c7b42269.png)
collect2.exe: error: ld returned 1 exit status

**Comment by oneway3124** [comment]
Some times there is one error when I am executing the command "mbed deploy".
[mbed] ERROR: An error occurred while unpacking library archive ".bld\.rev-7130f322cb7e.zip" in xxx

**Comment by zhuanaa** [comment]
did you come across "Couldn't find build tools in your program." at the step of "mbed new kws_simple_test --mbedlib"? Maybe this result in your problem.

**Comment by navsuda** [comment]
Hi  @oneway3124 
It looks like it is related to [#516](https://github.com/ARMmbed/mbed-cli/issues/516), [#448](https://github.com/ARMmbed/mbed-cli/issues/448).

**Comment by oneway3124** [comment]
@navsuda ,

Some check after your reviews, I think that these answers #516, #448, may not be the right ones. 
Can you give me some more information about mbed-cli?

**Comment by navsuda** [comment]
Hi @oneway3124,
If you have solved your environment issue, please consider closing the issue.

**Comment by navsuda** [comment]
Closing the issue due to inactivity, please reopen it if you still face the issue.

**Comment by jimmy9389** [comment]
Hi @oneway3124 I'm facing the exactly same problem you describe at first, could you please tell how you sovled it?
![微信截图_20190614182603](https://user-images.githubusercontent.com/35293340/59503023-eb63b500-8ed1-11e9-9158-979359bcb12d.png)
