### ISSUE TITLE
The accuracy is not very high 

### ISSUE THREAD

**Issue by sunjunlishi** [ARM-software/ML-KWS-for-MCU#29]
is not 16000hz，16bit，1 channel？

**Comment by sunjunlishi** [comment]
oh，i found it is very good。
if train more and more,It must be commercially available

**Comment by sunjunlishi** [comment]
When you train, how many voice files do you have in a word? If I add voice files, the training results will be more generalized.

**Comment by navsuda** [comment]
Hi @sunjunlishi,
This dataset consists of ~2500 per word, for exact numbers please see [this paper](https://arxiv.org/pdf/1804.03209.pdf) or check your extracted tar of the dataset.  Yes, detection accuracy  will improve if you add more meaningful data. 
Please consider closing the issue if you don't have any follow up questions.

**Comment by sunjunlishi** [comment]
thanks for your answer。’A‘ ’AO‘ will be recognized as  ‘off’，i think Adding an unknown sample，will be ok？

**Comment by ccnankai** [comment]
@sunjunlishi 
In the quantization process, how to get the value of the quantization ranges -- act_max in quant_test.py .
how to set the specific value of the parameter act_max ( x 0 0 0 0 0 0 0 0 0 0 0 ) ?
