### ISSUE TITLE
This error shows that "....might take a minute", however it cost one hour and still donot success.

### ISSUE THREAD

**Issue by oneway3124** [ARM-software/ML-KWS-for-MCU#32]
C:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment>mbed new kws_simple_tes
t --mbedlib
[mbed] Creating new program "kws_simple_test" (git)
[mbed] Adding library "mbed" from "https://mbed.org/users/mbed_official/code/mbe
d/builds" at latest revision in the current branch
[mbed] Downloading library build "5aab5a7997ee" (might take a minute)

**Comment by oneway3124** [comment]
C:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment>mbed new kws_simple_tes
t --mbedlib
[mbed] Creating new program "kws_simple_test" (git)
[mbed] Adding library "mbed" from "https://mbed.org/users/mbed_official/code/mbe
d/builds" at latest revision in the current branch
[mbed] Updating reference "mbed" -> "https://mbed.org/users/mbed_official/code/m
bed/builds/tip"
warning: LF will be replaced by CRLF in mbed.bld.
The file will have its original line endings in your working directory.
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK t
ools...

**Comment by oneway3124** [comment]
C:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment>cd kws_simple_test

C:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment\kws_simple_test>mbed de
ploy
[mbed] Updating library "mbed" to branch/tag "tip"
[mbed] Downloading library build "5aab5a7997ee" (might take a minute)

**Comment by navsuda** [comment]
This seems to be an issue with your mbed-cli environment. Can you try importing and building mbed-cli example [here](https://github.com/ARMmbed/mbed-cli#importing-an-existing-program) and raise an issue in mbed-cli if you have the same problem?

**Comment by oneway3124** [comment]
![333](https://user-images.githubusercontent.com/3787176/40225195-f6af15fe-5aba-11e8-8b12-683c0c87acdf.png)

![222](https://user-images.githubusercontent.com/3787176/40225213-00d04d00-5abb-11e8-993e-28b3d714270a.png)

![11](https://user-images.githubusercontent.com/3787176/40225219-04d33f84-5abb-11e8-8bd3-a12d69a34d03.png)

From the above pictures, I think that this issue may be created by package update. So Can you tell me which file is responsible for this?

**Comment by oneway3124** [comment]
The second picture is my local file storage which is compiled for latest successful compilation.

**Comment by oneway3124** [comment]
@navsuda Can you help me answer this question?

**Comment by oneway3124** [comment]
It seems to be ok now!

![_20180522160137](https://user-images.githubusercontent.com/3787176/40349508-6cda28f6-5dd9-11e8-8733-4232fc8e9791.png)

But, why is there some other compile error as the figure shows?

**Comment by navsuda** [comment]
Hi @oneway3124 
I do not understand the cause of your error, but it seems to be an error with mbed-cli specific to your environment. Can you try debugging it in a virtual-environment? Also, raise an issue in mbed-cli, some other users who have had this issue may be able to help you. 
I have added an example for FRDM-K64F, which can be built without mbed-cli [here](https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Deployment/Examples/simple_test_k64f_gcc). Using that as a starting point, you may be able to build it for any other mbed supported board.

**Comment by oneway3124** [comment]
OK, this environment has been installed on the laptop of my colleague, but the error looks like me.
Which virtual environment do you mean? virtualbox or vmware, I has tried it.
At the same time, I also raise one issue in mbed-cli, there is no useful answer for this question.
So, I am trying your new example for FRDM-K64F now.

**Comment by oneway3124** [comment]
![image](https://user-images.githubusercontent.com/3787176/40399561-a3d338e2-5e70-11e8-9572-f49b190dce4e.png)
@navsuda thanks for your help, I can compile the FRDM-K64F on the ubuntu system in the virtualbox.
Then, I will complete the remaining steps of NUCLEO_F411RE board. If there is some question, I will raise some isssue on this site. Thanks very much in advance.

**Comment by ccnankai** [comment]
@oneway3124 

In the quantization process, how to get the value of the quantization ranges -- act_max in quant_test.py .
how to set the specific value of the parameter act_max ( x 0 0 0 0 0 0 0 0 0 0 0 ) ?

**Comment by ccnankai** [comment]
@oneway3124  
你好，量化的时候   --act_max参数的值怎么确定的，从哪得来的  是1-128吗？
