### ISSUE TITLE
The mbed-cli error leading to the compiling error.

### ISSUE THREAD

**Issue by oneway3124** [ARM-software/ML-KWS-for-MCU#34]
Hi author,

I has tried so many method for this compiling issue. 
When I has done sucessfully mbed deploy , then mbed compile, some error shows as following.

![image](https://user-images.githubusercontent.com/3787176/40414971-4c274f84-5eac-11e8-835e-102e3a263fe0.png)

![image](https://user-images.githubusercontent.com/3787176/40414998-5c4382f2-5eac-11e8-8e77-141f82948f71.png)

the error log says, ....mbed.h: No such file or directory  ... compilation terminated.

But I use `find name mbed.h`
only shows
`./mbed/5aab5a7997ee/mbed.h`

So I can draw a conclusion the mbed-cli lead to the compiling error. So why will we use the previous version of mbed-cli.

@navsuda certainly, we also can continue to the gcc-arm toolchain development.
At the same time , we should keep the mbed-cli toolchain development.  What's your opinion?

**Comment by navsuda** [comment]
@oneway3124 ,
Sorry, I didn't get your question correctly. 
Both toolchains serve different sets of developer communities and hence are important. Please use the toolchain which works best for your purpose.

**Comment by navsuda** [comment]
Closing the issue due to inactivity, please reopen it if you still face the issue.

**Comment by ccnankai** [comment]
@oneway3124 
I've had the same problem.is it a version problem. how can I solve this problem?
