### ISSUE TITLE
Support for RNNs in CMSIS-5

### ISSUE THREAD

**Issue by 4p0pt0Z** [ARM-software/ML-KWS-for-MCU#36]
Hi, thanks for sharing the code !

Is there any plan to share code for running the RNNs presented in [the paper](https://arxiv.org/pdf/1711.07128.pdf) on MCU, as it has been done for DS_CNNs ? Maybe code in the CMSIS-5 library ?

Thank you

**Comment by navsuda** [comment]
Hi @4p0pt0Z,
No plans to add RNNs at this point, but you can refer to this GRU example in CMSIS-NN: https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/arm_nnexamples_gru.cpp
