### ISSUE TITLE
Quantization and scaling

### ISSUE THREAD

**Issue by pooyaww** [ARM-software/ML-KWS-for-MCU#53]
@navsuda 
In case of DNN, --act_max should have 5 parameters such as --act_max 32 30 30 30 30, while the DNN structure is made of 4 layers
```
void DNN::run_nn(q7_t* in_data, q7_t* out_data)
{
	// Run all layers
	
	// IP1 
	arm_fully_connected_q7(in_data, ip1_wt, IN_DIM, IP1_OUT_DIM, 1, 7, ip1_bias, ip1_out, vec_buffer);
        // RELU1
	arm_relu_q7(ip1_out, IP1_OUT_DIM);

	// IP2 
	arm_fully_connected_q7(ip1_out, ip2_wt, IP1_OUT_DIM, IP2_OUT_DIM, 2, 8, ip2_bias, ip2_out, vec_buffer);
        // RELU2
	arm_relu_q7(ip2_out, IP2_OUT_DIM);

	// IP3 
	arm_fully_connected_q7(ip2_out, ip3_wt, IP2_OUT_DIM, IP3_OUT_DIM, 2, 9, ip3_bias, ip3_out, vec_buffer);
        // RELU3
	arm_relu_q7(ip3_out, IP3_OUT_DIM);

	// IP4 
	arm_fully_connected_q7(ip3_out, ip4_wt, IP3_OUT_DIM, OUT_DIM, 0, 6, ip4_bias, out_data, vec_buffer);

}

```
How should I use these _5 --act_max values_ to scale _4 arm_fully_connected_q7()_ functions?

**Comment by navsuda** [comment]
Hi @pooyaww,
The 5 `act_max` values correspond to the input of first layer and 4 outputs of 4 FC layers. 
For quantizing the activations (and finding bias_shift, out_shift parameters), please see [Quant_guide](https://github.com/ARM-software/ML-KWS-for-MCU/blob/master/Deployment/Quant_guide.md#quantizing-kws-models). At the end, an example was provided which should help you understand the flow. 
Also, `--act_max` should be powers of 2 only (i.e. 16, 32, 64, ...) in order to do fixed-point quantization (Qm.n).

**Comment by reklessabandon** [comment]
For a 5 layer DS-CNN in the following structure:
CONV1
CONV2_DS
CONV2_PW
CONV3_DS
CONV3_PW
CONV4_DS
CONV4_PW
CONV5_DS
CONV5_PW
FINAL_FC

Why are there 12 act_max values required, and what do they related to?

**Comment by navsuda** [comment]
12 quantization ranges correspond to the 10 layers that you mentioned + 1 input layer + 1 average pooling layer prior to FINAL_FC.

**Comment by xujieuse** [comment]
@navsuda 
`arm_fully_connected_q7(in_data, ip1_wt, IN_DIM, IP1_OUT_DIM, 1, 7, ip1_bias, ip1_out, vec_buffer);`
Using quant_test.py, we get the quantized weights are of the format Q0.7 (i.e. in range -1,1) and the quantized biases have 8 bits for fractional point (i.e. range -0.5,0.5),So, the product (layer_input x weights) will have 9 bits in the fractional part (Q5.2 x Q0.7 = Qx.9) and biases need to be shifted left by 1 to get to the same representation (i.e. Qx.8<<1 = Qy.9). The layer output has 2 bits for fractional part (Q5.2), so the product (layer_input x weights) needs to be shifted right by 7 to get to Q5.2 format.

I want to know the meaning of the **9** in this code snippet `arm_fully_connected_q7(ip2_out, ip3_wt, IP2_OUT_DIM, IP3_OUT_DIM, 2, 9, ip3_bias, ip3_out, vec_buffer);`  and the layer output format ?

Here are the results of my run,How do I set the parameters of arm_fully_connected_q7?
fc1_W_0 number of wts/bias: (250, 144) dec bits: 7 max: (0.546875,0.54698676) min: (-0.46875,-0.46990475)
fc1_b_0 number of wts/bias: (144,) dec bits: 7 max: (0.5703125,0.570461) min: (-0.390625,-0.38928118)
fc2_W_0 number of wts/bias: (144, 144) dec bits: 8 max: (0.3515625,0.35170227) min: (-0.3828125,-0.38205004)
fc2_b_0 number of wts/bias: (144,) dec bits: 7 max: (0.5390625,0.5390561) min: (-0.5703125,-0.570904)
fc3_W_0 number of wts/bias: (144, 144) dec bits: 8 max: (0.4140625,0.41240978) min: (-0.3828125,-0.3826295)
fc3_b_0 number of wts/bias: (144,) dec bits: 7 max: (0.5703125,0.57072264) min: (-0.21875,-0.2217004)
final_fc_0 number of wts/bias: (144, 5) dec bits: 7 max: (0.3984375,0.40102214) min: (-0.90625,-0.9030826)
Variable_0 number of wts/bias: (5,) dec bits: 8 max: (0.265625,0.26646054) min: (-0.06640625,-0.06762873)

**Comment by ghost** [comment]
@pooyaww  @gm-jl    @navsuda 
In the quantization process, how to get the value of the quantization ranges -- act_max in quant_test.py .
Where do you get the specific value of the parameter act_max   ( x 0 0 0 0 0 0 0 0 0 0 0 ) ?

**Comment by pooyaww** [comment]
@ccnankai Please don't spam on Issues, instead spend your time on reading materials, codes, articles and other issues. Spamming does not work for open source society. 
Currently there is no automated process for finding the best set of maximum quantization values, you should start from the first layer and incrementally quantize each layer to get the optimum performance You need enough data to get the quantization function work properly as the script makes different sections for Training, Validation and Test, with not enough data you don't get to a working solution.

**Comment by ccnankai** [comment]
@pooyaww   
I am very sorry because I don't understand quantification. I will delete the extra question.
Is it to use 128, 64, 32, 16, 8, 4, 2, 1 for each layer，and select the one with high accuracy？

**Comment by pooyaww** [comment]
@ccnankai Yes, you are right. A greedy approach would lead you to an acceptable result, try levels in the same range you mentioned for the first layer while assigning zeros for other layers then check the accuracy, fix a level for the current layer, then go on until the last layer. It is exactly what has already been mentioned in the quantization tutorial of this repo.

**Comment by ccnankai** [comment]
@pooyaww 
According to this quantization method, layer by layer. The accuracy on the test set is very high, but  very low on stm32f74xxx , showing a word and rarely changes.

**Comment by wayne175** [comment]
> 12 quantization ranges correspond to the 10 layers that you mentioned + 1 input layer + 1 average pooling layer prior to FINAL_FC.

Is this correct?--act_max 32 0 0 0 0 0 0 0 0 0 0 0,   ds_cnn useing that --acc_max value.
