### ISSUE TITLE
Quantize weight

### ISSUE THREAD

**Issue by XiangZheng2017** [ARM-software/ML-KWS-for-MCU#55]
I have a question on quantize weight code you posted in Quant_guide.md. What if the absolute value of max_value or min_value is less than 1? In that case, int_bits would be negative... I was so confused about that snippet. Could anybody explain that a little bit more to me ? Thanks

**Comment by ccnankai** [comment]
@XiangZheng2017  
In the quantization process, how to get the value of the quantization ranges -- act_max in quant_test.py .
Where do you get the specific value of the parameter act_max ( x 0 0 0 0 0 0 0 0 0 0 0 ) ?
