### ISSUE TITLE
k64f build failure

### ISSUE THREAD

**Issue by JammyZhou** [ARM-software/ML-KWS-for-MCU#60]
Follow [instructions](https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Deployment) to build the test application for k64f platform, it failed as below:

make[1]: *** No rule to make target `Source/local_NN/arm_convolve_HWC_q7_basic_nonsquare.o', needed by `simple_test_k64f_gcc.elf'.  Stop.
make: *** [all] Error 2

**Comment by navsuda** [comment]
@JammyZhou, 
Updated the stale path in Makefile, that should fix your error.

**Comment by JammyZhou** [comment]
Thanks, it is working for me now
