### ISSUE TITLE
Deployment STM32F746NG

### ISSUE THREAD

**Issue by saichand07** [ARM-software/ML-KWS-for-MCU#87]
@yanyanem 
Could you tell me, how did you flash bin files on to the STM32F746NG Board (Linux OS), I copied the .bin file into DIS_F746NG driver ( device detection on windows OS). I saw the led blink on STM32 but I cant see words on display.
How to deal with this issue, could you please tell me how to solve ?

**Comment by eera-l** [comment]
Hi @saichand07, I am having the same problem. How did you solve it?
