### ISSUE TITLE
How to decide the bias_shift and out_shift for arm_fully_connected_q7?

### ISSUE THREAD

**Issue by bkanakietac** [ARM-software/ML-KWS-for-MCU#90]
I have a question with regards to choosing `bias_shift` and `output_shift` when using the `arm_fully_connected_q_7` function. I followed the steps as mentioned in quant guide and my input/output activation act_max values are 128, 32, 128 which produces best results.

Below is the output for the weights quant:

```
hidden_state_kernel_0 number of wts/bias: (164, 154) dec bits: 8 max: (0.390625,0.38991457) min: (-0.39453125,-0.39302412)
hidden_state_bias_0 number of wts/bias: (154,) dec bits: 6 max: (1.03125,1.0302253) min: (0.921875,0.91665226)
fully-connected_kernel_0 number of wts/bias: (154, 4) dec bits: 7 max: (0.515625,0.51286805) min: (-0.5625,-0.56017095)
fully-connected_bias_0 number of wts/bias: (4,) dec bits: 12 max: (0.02734375,0.027446348) min: (-0.022705078,-0.022610128)
```

I referred #51 and the example in quant guide, but following that:
input: Q7.0
hidden_out: Q5.2
output: Q7.0

For the hidden layer, 
**input x weights will have 8 bits in the fractional part (Q0 x Q8) and bias has 6 bits in the fractional part, so bias need to be shifted right? But there is no option for the right shift in the function.**
layer output has 2 bits for fractional part so the output needs to be shifted right by 6, which is good.

For the fully connected layer:
input x weights will have 9 bits in the fractional part (Q2 x Q7) and bias has 12 bits, so bias needs to be shifted left by 3, which is good
layer output has 0 bits in the fractional part, so the output needs to be shifted right by 9, which is good.

How do I handle the case in bold? Or is there something wrong in my understanding? Please advise.

Thanks!

**Comment by saichand07** [comment]
@bkanakietac 
how do you calculate bias_shift and output_shift manually ?
can you direct me to the code (where do we need to change in the code)

Thanks
