### ISSUE TITLE
How to change Qm.n format of the layers 

### ISSUE THREAD

**Issue by saichand07** [ARM-software/ML-KWS-for-MCU#98]
> DS-CNN_conv_1_weights_0 number of wts/bias: (10, 4, 1, 64) dec bits: 9 max: (0.064453125,0.06367729) min: (-0.18164062,-0.18208852)
DS-CNN_conv_1_biases_0 number of wts/bias: (64,) dec bits: 6 max: (0.953125,0.94953424) min: (-1.0625,-1.062875)
DS-CNN_conv_ds_1_dw_conv_depthwise_weights_0 number of wts/bias: (3, 3, 64, 1) dec bits: 4 max: (4.75,4.7435927) min: (-3.4375,-3.420028)
DS-CNN_conv_ds_1_dw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (2.1875,2.1897135) min: (-2.25,-2.2415664)
DS-CNN_conv_ds_1_pw_conv_weights_0 number of wts/bias: (1, 1, 64, 64) dec bits: 7 max: (0.875,0.87845683) min: (-0.8359375,-0.83616173)
DS-CNN_conv_ds_1_pw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (2.3125,2.3191066) min: (-1.46875,-1.4603163)
DS-CNN_conv_ds_2_dw_conv_depthwise_weights_0 number of wts/bias: (3, 3, 64, 1) dec bits: 5 max: (2.03125,2.0257235) min: (-2.0,-2.0027153)
DS-CNN_conv_ds_2_dw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (2.34375,2.3322163) min: (-1.9375,-1.9391298)
DS-CNN_conv_ds_2_pw_conv_weights_0 number of wts/bias: (1, 1, 64, 64) dec bits: 7 max: (0.703125,0.70520025) min: (-0.6640625,-0.66173273)
DS-CNN_conv_ds_2_pw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (3.5,3.4909253) min: (-2.09375,-2.1036189)
DS-CNN_conv_ds_3_dw_conv_depthwise_weights_0 number of wts/bias: (3, 3, 64, 1) dec bits: 6 max: (1.78125,1.7810903) min: (-1.375,-1.374446)
DS-CNN_conv_ds_3_dw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (2.40625,2.4154606) min: (-1.78125,-1.7686051)
DS-CNN_conv_ds_3_pw_conv_weights_0 number of wts/bias: (1, 1, 64, 64) dec bits: 7 max: (0.6328125,0.63158494) min: (-0.671875,-0.66837484)
DS-CNN_conv_ds_3_pw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (2.71875,2.724961) min: (-2.5625,-2.5521417)
DS-CNN_conv_ds_4_dw_conv_depthwise_weights_0 number of wts/bias: (3, 3, 64, 1) dec bits: 6 max: (1.859375,1.8600764) min: (-1.75,-1.7450227)
DS-CNN_conv_ds_4_dw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (1.78125,1.7884142) min: (-2.8125,-2.8018646)
DS-CNN_conv_ds_4_pw_conv_weights_0 number of wts/bias: (1, 1, 64, 64) dec bits: 7 max: (0.84375,0.8405113) min: (-0.8046875,-0.8074308)
DS-CNN_conv_ds_4_pw_conv_biases_0 number of wts/bias: (64,) dec bits: 5 max: (2.0625,2.0603654) min: (-1.84375,-1.8518366)
DS-CNN_fc1_weights_0 number of wts/bias: (64, 12) dec bits: 5 max: (2.0625,2.0600655) min: (-3.875,-3.8689475)
DS-CNN_fc1_biases_0 number of wts/bias: (12,) dec bits: 6 max: (1.109375,1.1048715) min: (-0.265625,-0.26571637)

from above data,
How to figure out the Qm.n format of the layers and How to shift the bias_shift and out_shift, 
I am very new to this topic, I read the quantization guide many times, I understand the example but I couldn't figured out this.

and how to tune the below parameters 
#define CONV2_DS_BIAS_LSHIFT 2
#define CONV2_DS_OUT_RSHIFT 5
#define CONV2_PW_BIAS_LSHIFT 4
#define CONV2_PW_OUT_RSHIFT 8

Please share your ideas on this topic.

**Comment by majianjia** [comment]
please refer to issues in cmsis. There are many discussion about it
